# Generated by Django 5.1.3 on 2024-11-24 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=255)),
                ('capacidade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(max_length=20)),
                ('cargo', models.CharField(max_length=50)),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crud.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(max_length=50)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('hora_evento', models.TimeField()),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.lugar')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm', models.CharField(max_length=20, unique=True)),
                ('especializacao', models.CharField(max_length=50)),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crud.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crud.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_consulta', models.DateField()),
                ('hora_consulta', models.TimeField()),
                ('receita', models.TextField(blank=True, null=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crud.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inscricao', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.evento')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.participante')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('tipo', models.CharField(max_length=50)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.cliente')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.mesa')),
            ],
        ),
        migrations.CreateModel(
            name='Itens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingredientes', models.TextField(blank=True, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Recepcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_recepcionista', models.CharField(max_length=100)),
                ('turno', models.CharField(max_length=20)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.funcionario')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.paciente')),
            ],
        ),
    ]
