# Generated by Django 5.1.3 on 2024-11-24 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_lugar_funcionario_evento_medico_paciente_consulta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=50)),
                ('objeto_id', models.PositiveIntegerField()),
                ('modelo', models.CharField(max_length=100)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('detalhes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
